#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".js\{0,1\}$")
if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

# Prettify all selected files
echo "\nPrettifying Files"
echo "$STAGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$STAGED_FILES" | xargs git add
echo "Prettifying Complete\n"

echo "\nValidating files"
npx lint-staged
echo "Validated files\n"npx lint-staged
